### ISSUE TITLE
Error extracting packages

### ISSUE THREAD

**Issue by ukulekek** [dcantrell/rpminspect#4] opened 2019-04-16 13:15 UTC
I'm trying to inspect packages with rpminspect. `rpminspect` works fine with some packages, but some of them raise an error during extracting packages. My OS is Fedora-29. The example of the error is next:
```
$ rpminspect -F json gcc-8.2.1-3.4.el8 gcc-8.2.1-3.5.el8
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/i686/gcc-debuginfo-8.2.1-3.5.el8.i686.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.5.el8.i386.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/i686/libstdc++-8.2.1-3.5.el8.i686.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/i686/gcc-c++-debuginfo-8.2.1-3.5.el8.i686.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.5.el8.i386.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/i686/gcc-8.2.1-3.5.el8.i686.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/i686/gcc-8.2.1-3.5.el8.i686/usr/bin/i686-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/i686/gcc-c++-8.2.1-3.5.el8.i686.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/i686/gcc-c++-8.2.1-3.5.el8.i686/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/gcc-c++-debuginfo-8.2.1-3.5.el8.ppc64le.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.5.el8.ppc64le.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/gcc-debuginfo-8.2.1-3.5.el8.ppc64le.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.5.el8.ppc64le.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/gcc-offload-nvptx-8.2.1-3.5.el8.ppc64le.rpm: Hard-link target './usr/lib/gcc/ppc64le-redhat-linux/8/accel/nvptx-none/libc.a' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/libstdc++-8.2.1-3.5.el8.ppc64le.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/gcc-c++-8.2.1-3.5.el8.ppc64le.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/gcc-c++-8.2.1-3.5.el8.ppc64le/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/gcc-8.2.1-3.5.el8.ppc64le.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/ppc64le/gcc-8.2.1-3.5.el8.ppc64le/usr/bin/ppc64le-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/s390x/gcc-c++-debuginfo-8.2.1-3.5.el8.s390x.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.5.el8.s390x.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/s390x/gcc-8.2.1-3.5.el8.s390x.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/s390x/gcc-8.2.1-3.5.el8.s390x/usr/bin/s390x-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/s390x/gcc-c++-8.2.1-3.5.el8.s390x.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/s390x/gcc-c++-8.2.1-3.5.el8.s390x/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/s390x/gcc-debuginfo-8.2.1-3.5.el8.s390x.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.5.el8.s390x.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/s390x/libstdc++-8.2.1-3.5.el8.s390x.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/libstdc++-8.2.1-3.5.el8.x86_64.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/gcc-offload-nvptx-8.2.1-3.5.el8.x86_64.rpm: Hard-link target './usr/lib/gcc/x86_64-redhat-linux/8/accel/nvptx-none/libc.a' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/gcc-8.2.1-3.5.el8.x86_64.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/gcc-8.2.1-3.5.el8.x86_64/usr/bin/x86_64-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/gcc-debuginfo-8.2.1-3.5.el8.x86_64.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.5.el8.x86_64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/gcc-c++-8.2.1-3.5.el8.x86_64.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/gcc-c++-8.2.1-3.5.el8.x86_64/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/x86_64/gcc-c++-debuginfo-8.2.1-3.5.el8.x86_64.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.5.el8.x86_64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/aarch64/libstdc++-8.2.1-3.5.el8.aarch64.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/aarch64/gcc-c++-debuginfo-8.2.1-3.5.el8.aarch64.rpm: Hard-link target './usr/lib/debug/usr/bin/aarch64-redhat-linux-c++-8.2.1-3.5.el8.aarch64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/aarch64/gcc-c++-8.2.1-3.5.el8.aarch64.rpm: Hard-link target './usr/bin/aarch64-redhat-linux-c++' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/aarch64/gcc-8.2.1-3.5.el8.aarch64.rpm: Hard-link target './usr/bin/aarch64-redhat-linux-gcc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/after/aarch64/gcc-debuginfo-8.2.1-3.5.el8.aarch64.rpm: Hard-link target './usr/lib/debug/usr/bin/aarch64-redhat-linux-gcc-8-8.2.1-3.5.el8.aarch64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/i686/gcc-debuginfo-8.2.1-3.4.el8.i686.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.4.el8.i386.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/i686/gcc-c++-debuginfo-8.2.1-3.4.el8.i686.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.4.el8.i386.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/i686/libstdc++-8.2.1-3.4.el8.i686.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/i686/gcc-c++-8.2.1-3.4.el8.i686.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/i686/gcc-c++-8.2.1-3.4.el8.i686/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/i686/gcc-8.2.1-3.4.el8.i686.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/i686/gcc-8.2.1-3.4.el8.i686/usr/bin/i686-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/gcc-c++-debuginfo-8.2.1-3.4.el8.ppc64le.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.4.el8.ppc64le.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/gcc-debuginfo-8.2.1-3.4.el8.ppc64le.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.4.el8.ppc64le.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/gcc-offload-nvptx-8.2.1-3.4.el8.ppc64le.rpm: Hard-link target './usr/lib/gcc/ppc64le-redhat-linux/8/accel/nvptx-none/libc.a' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/libstdc++-8.2.1-3.4.el8.ppc64le.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/gcc-c++-8.2.1-3.4.el8.ppc64le.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/gcc-c++-8.2.1-3.4.el8.ppc64le/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/gcc-8.2.1-3.4.el8.ppc64le.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/ppc64le/gcc-8.2.1-3.4.el8.ppc64le/usr/bin/ppc64le-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/s390x/gcc-debuginfo-8.2.1-3.4.el8.s390x.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.4.el8.s390x.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/s390x/libstdc++-8.2.1-3.4.el8.s390x.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/s390x/gcc-c++-8.2.1-3.4.el8.s390x.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/s390x/gcc-c++-8.2.1-3.4.el8.s390x/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/s390x/gcc-8.2.1-3.4.el8.s390x.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/s390x/gcc-8.2.1-3.4.el8.s390x/usr/bin/s390x-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/s390x/gcc-c++-debuginfo-8.2.1-3.4.el8.s390x.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.4.el8.s390x.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/gcc-8.2.1-3.4.el8.x86_64.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/gcc-8.2.1-3.4.el8.x86_64/usr/bin/x86_64-redhat-linux-gcc'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/gcc-c++-debuginfo-8.2.1-3.4.el8.x86_64.rpm: Hard-link target './usr/lib/debug/usr/bin/c++-8.2.1-3.4.el8.x86_64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/libstdc++-8.2.1-3.4.el8.x86_64.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/gcc-c++-8.2.1-3.4.el8.x86_64.rpm: Can't create '/var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/gcc-c++-8.2.1-3.4.el8.x86_64/usr/bin/g++'
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/gcc-debuginfo-8.2.1-3.4.el8.x86_64.rpm: Hard-link target './usr/lib/debug/usr/bin/gcc-8.2.1-3.4.el8.x86_64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/x86_64/gcc-offload-nvptx-8.2.1-3.4.el8.x86_64.rpm: Hard-link target './usr/lib/gcc/x86_64-redhat-linux/8/accel/nvptx-none/libc.a' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/aarch64/libstdc++-8.2.1-3.4.el8.aarch64.rpm: Hard-link target './usr/share/gcc-8/python/libstdcxx/__pycache__/__init__.cpython-36.opt-1.pyc' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/aarch64/gcc-debuginfo-8.2.1-3.4.el8.aarch64.rpm: Hard-link target './usr/lib/debug/usr/bin/aarch64-redhat-linux-gcc-8-8.2.1-3.4.el8.aarch64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/aarch64/gcc-c++-debuginfo-8.2.1-3.4.el8.aarch64.rpm: Hard-link target './usr/lib/debug/usr/bin/aarch64-redhat-linux-c++-8.2.1-3.4.el8.aarch64.debug' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/aarch64/gcc-c++-8.2.1-3.4.el8.aarch64.rpm: Hard-link target './usr/bin/aarch64-redhat-linux-c++' does not exist.
*** Error extracting /var/tmp/rpminspect/gcc-8.2.1.kLGi5d/before/aarch64/gcc-8.2.1-3.4.el8.aarch64.rpm: Hard-link target './usr/bin/aarch64-redhat-linux-gcc' does not exist.
rpminspect: inspect_emptyrpm.c:32: is_payload_empty: Assertion `filelist != NULL' failed.
[1]    15146 abort (core dumped)  rpminspect -F json gcc-8.2.1-3.4.el8 gcc-8.2.1-3.5.el8
```

**Comment by dcantrell** [comment] 2019-04-16 18:18
I was able to reproduce this locally on F-29 and am working on a fix.  Two problems found:

1) Peer detection needs to only run after both peers added (you wouldn't have seen this in the build you tried because peer detection hadn't been merged yet).
2) Hard link extraction is improperly handling the destination path.

Should have this fixed up soon.  Thanks for the report.

**Comment by dcantrell** [comment] 2019-04-16 19:40
Peer detection and hard link extraction have been fixed.  I've pushed changes and a new build should kick off in the copr repo momentarily.

**Closed** 2019-04-16 19:40 UTC

**Comment by hroncok** [comment] 2019-08-08 15:07
I see this, is it related?

```
$ rpm -q rpminspect 
rpminspect-0.2-0.1.201908021955git.fc30.x86_64

$ rpminspect -v python3-3.7.4-1.fc31 python3-3.7.4-3.fc31
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-debugsource-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-debuginfo-3.7.4-3.fc31.s390x.rpm...
*** Error extracting /var/tmp/rpminspect/python3-3.7.4.mJGoz3/after/s390x/python3-debuginfo-3.7.4-3.fc31.s390x.rpm: Can't create '/var/tmp/rpminspect/python3-3.7.4.mJGoz3/after/s390x/python3-debuginfo-3.7.4-3.fc31.s390x/usr/lib/debug/usr/bin/python3.7m-3.7.4-3.fc31.s390x.debug'
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-debug-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-test-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-tkinter-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-idle-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-devel-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-libs-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/s390x/python3-3.7.4-3.fc31.s390x.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-devel-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-debugsource-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-debug-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-libs-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-tkinter-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-test-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-debuginfo-3.7.4-3.fc31.ppc64le.rpm...
*** Error extracting /var/tmp/rpminspect/python3-3.7.4.mJGoz3/after/ppc64le/python3-debuginfo-3.7.4-3.fc31.ppc64le.rpm: Can't create '/var/tmp/rpminspect/python3-3.7.4.mJGoz3/after/ppc64le/python3-debuginfo-3.7.4-3.fc31.ppc64le/usr/lib/debug/usr/bin/python3.7m-3.7.4-3.fc31.ppc64le.debug'
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/ppc64le/python3-idle-3.7.4-3.fc31.ppc64le.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-tkinter-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-test-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-debuginfo-3.7.4-3.fc31.aarch64.rpm...
*** Error extracting /var/tmp/rpminspect/python3-3.7.4.mJGoz3/after/aarch64/python3-debuginfo-3.7.4-3.fc31.aarch64.rpm: Can't create '/var/tmp/rpminspect/python3-3.7.4.mJGoz3/after/aarch64/python3-debuginfo-3.7.4-3.fc31.aarch64/usr/lib/debug/usr/bin/python3.7m-3.7.4-3.fc31.aarch64.debug'
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-libs-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-debugsource-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-devel-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-idle-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/aarch64/python3-debug-3.7.4-3.fc31.aarch64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/x86_64/python3-libs-3.7.4-3.fc31.x86_64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/x86_64/python3-devel-3.7.4-3.fc31.x86_64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/x86_64/python3-idle-3.7.4-3.fc31.x86_64.rpm...
Downloading https://kojipkgs.fedoraproject.org/packages/python3/3.7.4/3.fc31/x86_64/python3-debug-3.7.4-3.fc31.x86_64.rpm...
...
```
